"""Declarative base and shared column conventions for all ORM models.

Two things are established here that are easy to add now and painful to retrofit.

**Deterministic constraint names.** PostgreSQL will invent a name for any unnamed
index, unique constraint or foreign key. Those generated names differ between
databases, which makes Alembic autogenerate produce spurious drops and creates,
and makes a migration that drops a constraint by name unreliable. The naming
convention below means every constraint has a predictable name derived from the
table and column.

**Timezone-aware timestamps everywhere.** ``TIMESTAMP WITHOUT TIME ZONE`` silently
discards offset information, so a value written from a machine in one timezone
reads back wrong elsewhere. Every timestamp in this schema is ``timestamptz``, and
defaults are generated by the *database* rather than by Python, so rows inserted
by a migration or by ``psql`` are stamped consistently with rows inserted by the
application.
"""

from __future__ import annotations

import datetime as dt

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Applied to every constraint SQLAlchemy creates. `%(column_0_name)s` expands to
# the first column involved, so `fk_chunks_paper_id_papers` describes itself.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by every model in the application."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """Adds ``created_at`` and ``updated_at`` maintained by the database.

    ``server_default`` and ``onupdate`` are used rather than Python defaults so the
    values are correct regardless of which client wrote the row — the application,
    an Alembic migration, or a manual ``psql`` session during debugging.
    """

    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        doc="When this row was first inserted.",
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        doc="When this row was last modified.",
    )
