"""initial schema

Revision ID: 6b80918d8944
Revises:
Create Date: 2026-09-28 00:52:41.405986+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6b80918d8944"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
        sa.UniqueConstraint("normalized_name", name="uq_authors_normalized_name"),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "run_type",
            sa.Enum(
                "INCREMENTAL", "BACKFILL", "MANUAL", name="runtype", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "PARTIAL",
                name="runstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("papers_fetched", sa.Integer(), nullable=False),
        sa.Column("papers_accepted", sa.Integer(), nullable=False),
        sa.Column("papers_skipped", sa.Integer(), nullable=False),
        sa.Column("papers_updated", sa.Integer(), nullable=False),
        sa.Column("papers_failed", sa.Integer(), nullable=False),
        sa.Column("chunks_indexed", sa.Integer(), nullable=False),
        sa.Column("triggered_by", sa.String(length=32), nullable=False),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_ingestion_runs_finished_after_started"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_index("ix_ingestion_runs_started_at", "ingestion_runs", ["started_at"], unique=False)
    op.create_index("ix_ingestion_runs_status", "ingestion_runs", ["status"], unique=False)
    op.create_table(
        "papers",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("arxiv_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_latest", sa.Boolean(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_source", sa.DateTime(timezone=True), nullable=False),
        sa.Column("primary_category", sa.String(length=64), nullable=False),
        sa.Column("categories", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("journal_ref", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("abs_url", sa.Text(), nullable=False),
        sa.Column("pdf_url", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_papers_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_papers")),
        sa.UniqueConstraint("arxiv_id", "version", name="uq_papers_arxiv_id_version"),
    )
    op.create_index("ix_papers_primary_category", "papers", ["primary_category"], unique=False)
    op.create_index("ix_papers_published_at", "papers", ["published_at"], unique=False)
    op.create_index(
        "uq_papers_arxiv_id_latest",
        "papers",
        ["arxiv_id"],
        unique=True,
        postgresql_where=sa.text("is_latest"),
    )
    op.create_table(
        "user_queries",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("insufficient_evidence", sa.Boolean(), nullable=False),
        sa.Column(
            "retrieval_mode",
            sa.Enum(
                "KEYWORD", "VECTOR", "HYBRID", name="retrievalmode", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("top_k", sa.Integer(), nullable=False),
        sa.Column("reranker_enabled", sa.Boolean(), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column("retrieval_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cited_papers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("chunks_retrieved", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("retrieval_ms", sa.Integer(), nullable=True),
        sa.Column("rerank_ms", sa.Integer(), nullable=True),
        sa.Column("generation_ms", sa.Integer(), nullable=True),
        sa.Column("total_ms", sa.Integer(), nullable=False),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("top_k > 0", name=op.f("ck_user_queries_top_k_positive")),
        sa.CheckConstraint("total_ms >= 0", name=op.f("ck_user_queries_total_ms_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_queries")),
        sa.UniqueConstraint("request_id", name="uq_user_queries_request_id"),
    )
    op.create_index("ix_user_queries_created_at", "user_queries", ["created_at"], unique=False)
    op.create_index(
        "ix_user_queries_prompt_version", "user_queries", ["prompt_version"], unique=False
    )
    op.create_index(
        "ix_user_queries_retrieval_mode", "user_queries", ["retrieval_mode"], unique=False
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("paper_id", sa.BigInteger(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("subsection", sa.Text(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("opensearch_doc_id", sa.String(length=128), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("chunk_index >= 0", name=op.f("ck_chunks_chunk_index_non_negative")),
        sa.CheckConstraint("token_count > 0", name=op.f("ck_chunks_token_count_positive")),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.id"], name=op.f("fk_chunks_paper_id_papers"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint("opensearch_doc_id", name="uq_chunks_opensearch_doc_id"),
        sa.UniqueConstraint("paper_id", "chunk_index", name="uq_chunks_paper_id_chunk_index"),
    )
    op.create_index("ix_chunks_content_hash", "chunks", ["content_hash"], unique=False)
    op.create_index("ix_chunks_indexed_at", "chunks", ["indexed_at"], unique=False)
    op.create_table(
        "document_processing_status",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("paper_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "PENDING",
                "DOWNLOADED",
                "EXTRACTED",
                "CHUNKED",
                "EMBEDDED",
                "INDEXED",
                "FAILED",
                "SKIPPED",
                name="processingstage",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_error_type", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_document_processing_status_attempts_non_negative")
        ),
        sa.CheckConstraint(
            "max_attempts >= 1", name=op.f("ck_document_processing_status_max_attempts_positive")
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
            name=op.f("fk_document_processing_status_paper_id_papers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_processing_status")),
        sa.UniqueConstraint("paper_id", name="uq_document_processing_status_paper_id"),
    )
    op.create_index(
        "ix_document_processing_status_stage_retry",
        "document_processing_status",
        ["stage", "next_retry_at"],
        unique=False,
    )
    op.create_table(
        "document_texts",
        sa.Column("paper_id", sa.BigInteger(), nullable=False),
        sa.Column("full_text", sa.Text(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "PYMUPDF", "OCR", "NONE", name="extractionmethod", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
            name=op.f("fk_document_texts_paper_id_papers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("paper_id", name=op.f("pk_document_texts")),
    )
    op.create_table(
        "failed_documents",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("paper_id", sa.BigInteger(), nullable=True),
        sa.Column("arxiv_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column(
            "stage",
            sa.Enum(
                "PENDING",
                "DOWNLOADED",
                "EXTRACTED",
                "CHUNKED",
                "EMBEDDED",
                "INDEXED",
                "FAILED",
                "SKIPPED",
                name="processingstage",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("error_type", sa.String(length=128), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
            name=op.f("fk_failed_documents_paper_id_papers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_failed_documents_run_id_ingestion_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_failed_documents")),
    )
    op.create_index("ix_failed_documents_arxiv_id", "failed_documents", ["arxiv_id"], unique=False)
    op.create_index(
        "ix_failed_documents_resolved_at", "failed_documents", ["resolved_at"], unique=False
    )
    op.create_index("ix_failed_documents_stage", "failed_documents", ["stage"], unique=False)
    op.create_table(
        "paper_authors",
        sa.Column("paper_id", sa.BigInteger(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_paper_authors_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
            name=op.f("fk_paper_authors_author_id_authors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
            name=op.f("fk_paper_authors_paper_id_papers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("paper_id", "author_id", name=op.f("pk_paper_authors")),
        sa.UniqueConstraint("paper_id", "position", name="uq_paper_authors_paper_id_position"),
    )
    op.create_table(
        "pipeline_checkpoints",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("checkpoint_key", sa.String(length=128), nullable=False),
        sa.Column("last_updated_at_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_arxiv_id", sa.String(length=32), nullable=True),
        sa.Column("last_run_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["last_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_pipeline_checkpoints_last_run_id_ingestion_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_checkpoints")),
        sa.UniqueConstraint("checkpoint_key", name="uq_pipeline_checkpoints_checkpoint_key"),
    )
    op.create_table(
        "user_feedback",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("query_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "rating",
            sa.Enum("POSITIVE", "NEGATIVE", name="feedbackrating", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["user_queries.id"],
            name=op.f("fk_user_feedback_query_id_user_queries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_feedback")),
        sa.UniqueConstraint("query_id", name="uq_user_feedback_query_id"),
    )
    op.create_index("ix_user_feedback_created_at", "user_feedback", ["created_at"], unique=False)
    op.create_index("ix_user_feedback_rating", "user_feedback", ["rating"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_feedback_rating", table_name="user_feedback")
    op.drop_index("ix_user_feedback_created_at", table_name="user_feedback")
    op.drop_table("user_feedback")
    op.drop_table("pipeline_checkpoints")
    op.drop_table("paper_authors")
    op.drop_index("ix_failed_documents_stage", table_name="failed_documents")
    op.drop_index("ix_failed_documents_resolved_at", table_name="failed_documents")
    op.drop_index("ix_failed_documents_arxiv_id", table_name="failed_documents")
    op.drop_table("failed_documents")
    op.drop_table("document_texts")
    op.drop_index(
        "ix_document_processing_status_stage_retry", table_name="document_processing_status"
    )
    op.drop_table("document_processing_status")
    op.drop_index("ix_chunks_indexed_at", table_name="chunks")
    op.drop_index("ix_chunks_content_hash", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("ix_user_queries_retrieval_mode", table_name="user_queries")
    op.drop_index("ix_user_queries_prompt_version", table_name="user_queries")
    op.drop_index("ix_user_queries_created_at", table_name="user_queries")
    op.drop_table("user_queries")
    op.drop_index(
        "uq_papers_arxiv_id_latest", table_name="papers", postgresql_where=sa.text("is_latest")
    )
    op.drop_index("ix_papers_published_at", table_name="papers")
    op.drop_index("ix_papers_primary_category", table_name="papers")
    op.drop_table("papers")
    op.drop_index("ix_ingestion_runs_status", table_name="ingestion_runs")
    op.drop_index("ix_ingestion_runs_started_at", table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_table("authors")
    # ### end Alembic commands ###
